//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOINTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPOINTMENT()
        {
            this.BILLs = new HashSet<BILL>();
        }
    
        public int Appointment_id { get; set; }
        public Nullable<int> ID_Patient { get; set; }
        public Nullable<int> ID_Dep { get; set; }
        public Nullable<System.DateTime> app_date { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual PATIENT PATIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
    }
}
