//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOINTMENT
    {
        public int Appointment_id { get; set; }
        public int ID_Patient { get; set; }
        public int ID_Dep { get; set; }
        public System.DateTime app_date { get; set; }
        public bool p_turn { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual PATIENT PATIENT { get; set; }
    }
}
