//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR
    {
        public int ID_Doc { get; set; }
        public string DOC_Name { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ID_Dep { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
    }
}
