//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public string ID_Employee { get; set; }
        public string employee_name { get; set; }
        public double Salary { get; set; }
        public string Job { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string Town { get; set; }
        public string Address { get; set; }
        public byte[] Image { get; set; }
        public string Password { get; set; }
    }
}
