//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAL_EXAMINATIONS_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICAL_EXAMINATIONS_TYPES()
        {
            this.MEDICAL_EXAMINATIONS = new HashSet<MEDICAL_EXAMINATIONS>();
        }
    
        public int MeType_ID { get; set; }
        public string Type { get; set; }
        public Nullable<double> Type_Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICAL_EXAMINATIONS> MEDICAL_EXAMINATIONS { get; set; }
    }
}
