//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAL_EXAMINATIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICAL_EXAMINATIONS()
        {
            this.BILLs = new HashSet<BILL>();
        }
    
        public int ME_ID { get; set; }
        public Nullable<int> MeType { get; set; }
        public Nullable<System.DateTime> ME_DATE { get; set; }
        public Nullable<int> ID_Patient { get; set; }
        public Nullable<int> P_OUT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        public virtual MEDICAL_EXAMINATIONS_TYPE MEDICAL_EXAMINATIONS_TYPE { get; set; }
        public virtual PATIENT PATIENT { get; set; }
    }
}
