//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacy_Bill
    {
        public int PH_Bill_ID { get; set; }
        public int ID_Patient { get; set; }
        public int Medicine_Code { get; set; }
    
        public virtual PATIENT PATIENT { get; set; }
        public virtual PHARMACY PHARMACY { get; set; }
    }
}
